### ISSUE TITLE
Lỗi giao diện cho _ProductCategoryItemPartial

### ISSUE THREAD

**Issue by lekhasy** [lekhasy/UpupNetFramework#1]
Trên ttrang chủ đang bị lỗi hình ảnh nếu quá dài thì sẽ che mất text phía trên.
_ProductItemPartial có thể cũng đang gặp tình trạng tương tự.
Bên cạnh đó carousel cho product category trên trang chủ đang hiển thị 2 page (có 2 dấu chấm phía trên bên phải khung carousel) nhưng thực tế mới chỉ có 2 sản phẩm.

**Comment by thangphuong** [comment]
Fixed
