### ISSUE TITLE
Cập nhật chỉnh sửa buổi họp thứ 3 (24/11/2017)

### ISSUE THREAD

**Issue by thangphuong** [lekhasy/UpupNetFramework#11]
- search thiếu key description
- chi tiet sp => cho vao don hàng => 2 lựa chọn (PO cũ và PO mớ) => chọn po cũ => luu tam PO mới và active don hang cu
- ct san pham => thay doi ngày giao chi tiet thành "vd:3 ngay"
- bỏ đặt hang nhanh
- dời 2 nút đơn hàng lên trên, dời tìm kiếm qua trái
- liên hệ => CSKH => link huong dan su dung o tren, thong tin lien hệ phía dưới
- danh sach don hang => disable nut xoa khi trang thai đon hang đang xử lý ngoại trừ đơn hàng tạm và thành công
- danh sach don hang => nut chi tiet => giỏ hàng, xet trang thai mà cho chỉnh sửa.
- Chi tiết DH => Dat hang => hiện bảng chọn phương thức thanh toán => xac nhận => hiển thị "thông báo đặt hang thanh cong" (cau từ tự chọn)
- Admin sản phẩm thêm nút xem tổng quát => hiện tất cả các chi tiết từng biến thể sp

**Comment by thangphuong** [comment]
Vấn đề còn tồn động:
- search thiếu key description
- chi tiet sp => cho vao don hàng => 2 lựa chọn (PO cũ và PO mớ) => chọn po cũ => luu tam PO mới và active don hang cu
- danh sach don hang => disable nut xoa khi trang thai đon hang đang xử lý ngoại trừ đơn hàng tạm và thành công
- danh sach don hang => nut chi tiet => giỏ hàng, xet trang thai mà cho chỉnh sửa.
- Chi tiết DH => Dat hang => hiện bảng chọn phương thức thanh toán => xac nhận => hiển thị "thông báo đặt hang thanh cong" (cau từ tự chọn)

**Comment by lekhasy** [comment]
Vấn đề còn tồn động:

- danh sach don hang => disable nut xoa khi trang thai đon hang đang xử lý ngoại trừ đơn hàng tạm và thành công
- danh sach don hang => nut chi tiet => giỏ hàng, xet trang thai mà cho chỉnh sửa.
- Chi tiết DH => Dat hang => hiện bảng chọn phương thức thanh toán => xac nhận => hiển thị "thông báo đặt hang thanh cong" (cau từ tự chọn)

**Comment by lekhasy** [comment]
Vấn đề còn tồn động:
Chi tiết DH => Dat hang => hiện bảng chọn phương thức thanh toán => xac nhận => hiển thị "thông báo đặt hang thanh cong" (cau từ tự chọn)
