### ISSUE TITLE
Phần OnHand cần xem xét lại luồng dữ liệu và điều chỉnh khi PO thay đổi trạng thái

### ISSUE THREAD

**Issue by lekhasy** [lekhasy/UpupNetFramework#14]

**Comment by lekhasy** [comment]
Các lưu ý khi xóa đơn hàng:
Khi trạng thái đang là Ordered: trừ vào Reserved
Khi trạng thái đang là Paid hoặc cao hơn: trừ vào Reserved và OnHand
Không trừ j cả khi trạng thái đang là Temp.

Các thao tác chuyển đổi trạng thái cũng phải cộng vào Reserved/Onhand tương tự như trên.

**Comment by lekhasy** [comment]
Để release kịp hạn, tạm thời không dung field reserve mà select trực tiếp số lượng reserve trên hệ thống của product. 1 PO ở trạng thái ordered sẽ được tính là đang reserve số product đó.
Logic cho Onhand giữ nguyên.
OnHand sẽ được trừ khi Paid, được cộng lại khi hủy phiếu.

**Comment by lekhasy** [comment]
a @thangphuong , anh thêm code vào admin, chỗ nào chuyển trạng thái về Paid thì trừ onhand, chỗ nào hủy phiếu thì cộng lại dùm em.

**Comment by thangphuong** [comment]
Fixed
