### ISSUE TITLE
Các vấn đề còn tồn đọng

### ISSUE THREAD

**Issue by thangphuong** [lekhasy/UpupNetFramework#15]
- Chổ chi tiết sản phẩm, khi chọn thêm vào đơn hàng cũ, em lấy lên nhớ lọc điều kiện là đơn hàng tạm mới cho thêm nha.
- Khi đơn hàng hoàn thành nhớ trừ lại số lượng đã đặt vào số lượng tồn kho nha.
- Đặt hàng thành công => Sau khi khách hàng chọn xong phương thức nhấn ok, gởi cái mail xác nhận đơn hàng cho khách, và 1 mail thông báo cho admin, trước khi gửi nhớ hiện thông báo đơn hàng đã được đặt thành công, chúng tôi sẽ liên lạc với bạn ngay khi có thể.
- Ngày giao hàng bi giờ không tính cụ thể nữa mà cứ hiện số ngày giao ra thôi. Ví dụ: 3 ngày thay vì ngày hiện tại + 3

**Comment by lekhasy** [comment]
- Khi đơn hàng hoàn thành nhớ trừ lại số lượng đã đặt vào số lượng tồn kho nha.
- Đặt hàng thành công => Sau khi khách hàng chọn xong phương thức nhấn ok, gởi cái mail xác nhận -
đơn hàng cho khách, và 1 mail thông báo cho admin, trước khi gửi nhớ hiện thông báo đơn hàng đã được đặt thành công, chúng tôi sẽ liên lạc với bạn ngay khi có thể.
- Ngày giao hàng bi giờ không tính cụ thể nữa mà cứ hiện số ngày giao ra thôi. Ví dụ: 3 ngày thay vì ngày hiện tại + 3

**Comment by lekhasy** [comment]
Đặt hàng thành công => Sau khi khách hàng chọn xong phương thức nhấn ok, gởi cái mail xác nhận -
đơn hàng cho khách, và 1 mail thông báo cho admin, trước khi gửi nhớ hiện thông báo đơn hàng đã được đặt thành công, chúng tôi sẽ liên lạc với bạn ngay khi có thể.
